### ISSUE TITLE
missing file: tsubame.yaml

### ISSUE THREAD

**Issue by Huatsing-Lau** [ohuelab/SpatialPPIv2#2]
When running the command:
`python dataset_generator.py --split train --workers 8 --biogrid datasets/BIOGRID-ALL-4.4.238.tab3.txt`
I encountered the following error:
`FileNotFoundError: [Errno 2] No such file or directory: './config/tsubame.yaml'`
It seems that the file ./config/tsubame.yaml is missing from the repository. Could you please provide this file?

Or should I set the config as **/default.yaml**?

**Comment by perseids2032** [comment]
We have been updating the code repository recently. The update has been completed. Please pull the latest version for use.
